import 'package:saccm/constants/transaction_ui_text.dart';
import 'package:saccm/features/auth/presentation/providers/simple_auth_provider.dart';
import 'package:saccm/features/home/presentation/pages/home_nav_index.dart';

/// Seed สำหรับตาราง legacy [nav_menu_item] (อัปเกรด v19→v20 เท่านั้น — แอปใช้ [app_menu] ที่ v21)
abstract final class NavMenuSeedData {
  static List<Map<String, Object?>> sqliteRows({String? lastModified}) {
    final ts = lastModified ?? DateTime.now().toIso8601String();
    return <Map<String, Object?>>[
      {
        'id': 'home',
        'nav_index': HomeNavIndex.home,
        'section_title': 'ภาพรวม',
        'section_sort': 0,
        'item_sort': 0,
        'label': TransactionUiText.home,
        'icon_key': 'home_rounded',
        'required_permission': PermissionKey.navHome,
        'is_active': 1,
        'lastModified': ts,
      },
      {
        'id': 'income',
        'nav_index': HomeNavIndex.income,
        'section_title': TransactionUiText.navSectionTransactions,
        'section_sort': 1,
        'item_sort': 0,
        'label': TransactionUiText.incomeRecord,
        'icon_key': 'south_rounded',
        'required_permission': PermissionKey.navIncome,
        'is_active': 1,
        'lastModified': ts,
      },
      {
        'id': 'expense_req',
        'nav_index': HomeNavIndex.expenseReq,
        'section_title': TransactionUiText.navSectionTransactions,
        'section_sort': 1,
        'item_sort': 1,
        'label': TransactionUiText.expenseReqTabLabel,
        'icon_key': 'request_quote_outlined',
        'required_permission': PermissionKey.navExpenseReq,
        'is_active': 1,
        'lastModified': ts,
      },
      {
        'id': 'expense',
        'nav_index': HomeNavIndex.expense,
        'section_title': TransactionUiText.navSectionTransactions,
        'section_sort': 1,
        'item_sort': 2,
        'label': TransactionUiText.expenseVoucherRecord,
        'icon_key': 'north_rounded',
        'required_permission': PermissionKey.navExpense,
        'is_active': 1,
        'lastModified': ts,
      },
      {
        'id': 'loan',
        'nav_index': HomeNavIndex.loan,
        'section_title': TransactionUiText.navSectionTransactions,
        'section_sort': 1,
        'item_sort': 3,
        'label': TransactionUiText.loanRecord,
        'icon_key': 'account_balance_rounded',
        'required_permission': PermissionKey.navLoan,
        'is_active': 1,
        'lastModified': ts,
      },
      {
        'id': 'approval',
        'nav_index': HomeNavIndex.approval,
        'section_title': TransactionUiText.navSectionApprovalExpense,
        'section_sort': 2,
        'item_sort': 0,
        'label': TransactionUiText.approvalRecord,
        'icon_key': 'task_alt_rounded',
        'required_permission': PermissionKey.approvalView,
        'is_active': 1,
        'lastModified': ts,
      },
      {
        'id': 'reports',
        'nav_index': HomeNavIndex.reports,
        'section_title': TransactionUiText.navSectionApprovalExpense,
        'section_sort': 2,
        'item_sort': 1,
        'label': TransactionUiText.financeReport,
        'icon_key': 'bar_chart_rounded',
        'required_permission': PermissionKey.navReports,
        'is_active': 1,
        'lastModified': ts,
      },
      {
        'id': 'setting',
        'nav_index': HomeNavIndex.setting,
        'section_title': 'ระบบ',
        'section_sort': 3,
        'item_sort': 0,
        'label': TransactionUiText.systemSetting,
        'icon_key': 'settings_rounded',
        'required_permission': PermissionKey.settingView,
        'is_active': 1,
        'lastModified': ts,
      },
      {
        'id': 'usage_guide',
        'nav_index': HomeNavIndex.usageGuide,
        'section_title': 'ระบบ',
        'section_sort': 3,
        'item_sort': 1,
        'label': TransactionUiText.usageFlowHelperNavLabel,
        'icon_key': 'menu_book_outlined',
        'required_permission': PermissionKey.navUsageGuide,
        'is_active': 1,
        'lastModified': ts,
      },
      {
        'id': 'logout',
        'nav_index': HomeNavIndex.logout,
        'section_title': '',
        'section_sort': 999,
        'item_sort': 0,
        'label': TransactionUiText.exitProgram,
        'icon_key': 'logout_rounded',
        'required_permission': PermissionKey.navLogout,
        'is_active': 1,
        'lastModified': ts,
      },
    ];
  }
}
