import 'package:saccm/constants/transaction_ui_text.dart';
import 'package:saccm/features/auth/presentation/providers/simple_auth_provider.dart';
import 'package:saccm/features/home/presentation/pages/home_nav_index.dart';

/// Seed ตาราง [app_menu] — โครง parent_id แบบ link tree
abstract final class AppMenuSeedData {
  static List<Map<String, Object?>> sqliteRows({String? lastModified}) {
    final ts = lastModified ?? DateTime.now().toIso8601String();
    return <Map<String, Object?>>[
      {
        'id': 1,
        'parent_id': null,
        'slug': 'section_transactions',
        'name_th': TransactionUiText.navSectionTransactions,
        'name_en': 'section_transactions',
        'route_key': null,
        'required_permission': null,
        'icon_key': null,
        'sort_order': 1,
        'nav_index': null,
        'is_active': 1,
        'last_modified': ts,
      },
      {
        'id': 2,
        'parent_id': 1,
        'slug': 'income',
        'name_th': TransactionUiText.incomeRecord,
        'name_en': 'income',
        'route_key': 'income',
        'required_permission': PermissionKey.navIncome,
        'icon_key': 'south_rounded',
        'sort_order': 0,
        'nav_index': HomeNavIndex.income,
        'is_active': 1,
        'last_modified': ts,
      },
      {
        'id': 13,
        'parent_id': 1,
        'slug': 'expense_req',
        'name_th': TransactionUiText.expenseReqTabLabel,
        'name_en': 'expense_req',
        'route_key': 'expense_req',
        'required_permission': PermissionKey.navExpenseReq,
        'icon_key': 'request_quote_outlined',
        'sort_order': 1,
        'nav_index': HomeNavIndex.expenseReq,
        'is_active': 1,
        'last_modified': ts,
      },
      {
        'id': 3,
        'parent_id': 1,
        'slug': 'expense',
        'name_th': TransactionUiText.expenseVoucherRecord,
        'name_en': 'expense',
        'route_key': 'expense',
        'required_permission': PermissionKey.navExpense,
        'icon_key': 'north_rounded',
        'sort_order': 2,
        'nav_index': HomeNavIndex.expense,
        'is_active': 1,
        'last_modified': ts,
      },
      {
        'id': 4,
        'parent_id': 1,
        'slug': 'loan',
        'name_th': TransactionUiText.loanRecord,
        'name_en': 'loan',
        'route_key': 'loan',
        'required_permission': PermissionKey.navLoan,
        'icon_key': 'account_balance_rounded',
        'sort_order': 3,
        'nav_index': HomeNavIndex.loan,
        'is_active': 1,
        'last_modified': ts,
      },
      {
        'id': 5,
        'parent_id': null,
        'slug': 'section_approval_reports',
        'name_th': TransactionUiText.navSectionApprovalExpense,
        'name_en': 'section_approval_expense',
        'route_key': null,
        'required_permission': null,
        'icon_key': null,
        'sort_order': 2,
        'nav_index': null,
        'is_active': 1,
        'last_modified': ts,
      },
      {
        'id': 6,
        'parent_id': 5,
        'slug': 'approval',
        'name_th': TransactionUiText.approvalRecord,
        'name_en': 'approval',
        'route_key': 'approval',
        'required_permission': PermissionKey.approvalView,
        'icon_key': 'task_alt_rounded',
        'sort_order': 0,
        'nav_index': HomeNavIndex.approval,
        'is_active': 1,
        'last_modified': ts,
      },
      {
        'id': 7,
        'parent_id': 5,
        'slug': 'reports',
        'name_th': TransactionUiText.financeReport,
        'name_en': 'reports',
        'route_key': 'reports',
        'required_permission': PermissionKey.navReports,
        'icon_key': 'bar_chart_rounded',
        'sort_order': 1,
        'nav_index': HomeNavIndex.reports,
        'is_active': 1,
        'last_modified': ts,
      },
      {
        'id': 10,
        'parent_id': null,
        'slug': 'section_register',
        'name_th': 'ทะเบียนคุมและเอกสาร',
        'name_en': 'section_register',
        'route_key': null,
        'required_permission': null,
        'icon_key': null,
        'sort_order': 3,
        'nav_index': null,
        'is_active': 1,
        'last_modified': ts,
      },
      {
        'id': 11,
        'parent_id': 10,
        'slug': 'register',
        'name_th': 'ทะเบียนคุม',
        'name_en': 'register',
        'route_key': 'register',
        'required_permission': PermissionKey.navRegister,
        'icon_key': 'fact_check_outlined',
        'sort_order': 0,
        'nav_index': HomeNavIndex.register,
        'is_active': 1,
        'last_modified': ts,
      },
      {
        'id': 12,
        'parent_id': 10,
        'slug': 'forms',
        'name_th': 'แบบฟอร์มเอกสาร',
        'name_en': 'forms',
        'route_key': 'forms',
        'required_permission': PermissionKey.navForms,
        'icon_key': 'description_outlined',
        'sort_order': 1,
        'nav_index': HomeNavIndex.forms,
        'is_active': 1,
        'last_modified': ts,
      },
      {
        'id': 8,
        'parent_id': null,
        'slug': 'section_system',
        'name_th': 'ระบบ',
        'name_en': 'section_system',
        'route_key': null,
        'required_permission': null,
        'icon_key': null,
        'sort_order': 4,
        'nav_index': null,
        'is_active': 1,
        'last_modified': ts,
      },
      {
        'id': 9,
        'parent_id': 8,
        'slug': 'usage_guide',
        'name_th': TransactionUiText.usageFlowHelperNavLabel,
        'name_en': 'usage_guide',
        'route_key': 'usage_guide',
        'required_permission': PermissionKey.navUsageGuide,
        'icon_key': 'menu_book_outlined',
        'sort_order': 1,
        'nav_index': HomeNavIndex.usageGuide,
        'is_active': 1,
        'last_modified': ts,
      },
    ];
  }
}
